version: '3'
services:
  backend:
    build:
      context: ./Backend
      dockerfile: dockerfile
    ports:
      - "5000:5000"
  frontend:
    build:
      context: ./client
      dockerfile: dockerfile
    ports:
      - "4000:4000"
